const NS='http://www.w3.org/2000/svg';
const el={svg:document.getElementById('memorySvg'),numbers:document.getElementById('numbers'),path:document.getElementById('path'),stream:document.getElementById('streamLabel'),hud:document.getElementById('hud'),answer:document.getElementById('answerLine'),form:document.getElementById('startCard'),input:document.getElementById('questionInput'),replay:document.getElementById('replayBtn')};
let playback=0,lastQuestion='';
const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));
function svgNode(name,attrs={},value=''){const e=document.createElementNS(NS,name);Object.entries(attrs).forEach(([k,v])=>e.setAttribute(k,v));e.textContent=value;return e}
function text(x,y,value,cls){return svgNode('text',{x,y,class:cls},value)}
function tokenise(value){return value.trim().split(/\s+/).filter(Boolean).flatMap(word=>word.length>7?[word.slice(0,Math.ceil(word.length/2)),word.slice(Math.ceil(word.length/2))]:[word])}
function answerFor(question){const key=tokenise(question).slice(-1)[0]||'질문';return ['입력을','기억하고,',key+'에','답을','만듭니다.']}
function digits(value){return [...value].map(char=>char.codePointAt(0)).join('')}
function setNumbers(token,index){const chunks=(digits(token).match(/.{1,6}/g)||['0']).slice(0,7);el.numbers.replaceChildren(...chunks.map((value,i)=>{const n=document.createElement('span');n.className='number'+(i===index?' hot':'');n.textContent=value;return n}))}
function gate(g,x,y,kind){g.append(svgNode('rect',{x:x-10,y:y-10,width:20,height:20,class:'gate'}));g.append(svgNode('path',{d:kind==='σ'?`M ${x-6} ${y+3} C ${x-2} ${y+7} ${x+2} ${y-7} ${x+6} ${y-3}`:`M ${x-7} ${y+5} L ${x-2} ${y+5} C ${x+2} ${y+5} ${x+2} ${y-5} ${x+7} ${y-5}`,class:'glyph'}))}
function makeCell(i,x,labelValue){const g=svgNode('g',{class:'cell'}),top=130,mid=235,bottom=340;g.append(svgNode('line',{x1:x,y1:top,x2:x,y2:bottom,class:'vertical'}));[top,mid,bottom].forEach(y=>g.append(svgNode('circle',{cx:x,cy:y,r:29,class:'glow'})));g.append(svgNode('circle',{cx:x,cy:top,r:5,class:'tap'}),svgNode('circle',{cx:x,cy:bottom,r:5,class:'tap'}),svgNode('path',{d:`M ${x} ${bottom} V ${mid+13} M ${x} ${mid-13} V ${top}`,class:'cell-wire'}));gate(g,x,280,'σ');gate(g,x,190,'t');g.append(text(x+32,127,'×','operator'),text(x+59,127,'+','operator'),text(x+32,337,'×','operator'),text(x+59,337,'+','operator'),text(x,106,`c${i}`,'tiny'),text(x,371,labelValue.slice(0,6),'tiny'),svgNode('circle',{cx:x,cy:230,r:8,class:'pulse'}));return g}
function buildCircuit(steps){const defs=svgNode('defs'),blur=svgNode('filter',{id:'blur',x:'-100%',y:'-100%',width:'300%',height:'300%'}),shine=svgNode('filter',{id:'shine',x:'-100%',y:'-100%',width:'300%',height:'300%'});blur.append(svgNode('feGaussianBlur',{stdDeviation:'13'}));shine.append(svgNode('feGaussianBlur',{stdDeviation:'3',result:'b'}),svgNode('feMerge'));shine.lastChild.append(svgNode('feMergeNode',{in:'b'}),svgNode('feMergeNode',{in:'SourceGraphic'}));defs.append(blur,shine);el.svg.replaceChildren(defs,text(26,121,'LONG TERM MEMORY','rowLabel'),text(26,143,'cell state cₜ · what survives','rowSub'),text(26,319,'SHORT TERM MEMORY','rowLabel'),text(26,341,'hidden state hₜ · what matters now','rowSub'),svgNode('line',{x1:205,y1:130,x2:1140,y2:130,class:'rail'}),svgNode('line',{x1:205,y1:340,x2:1140,y2:340,class:'rail'}),text(202,135,'0','tiny'),text(202,345,'0','tiny'));const gap=Math.min(140,850/Math.max(steps.length-1,1));steps.forEach((step,i)=>el.svg.append(makeCell(i,250+i*gap,step.token)))}
function mark(index){[...el.svg.querySelectorAll('.cell')].forEach((cell,i)=>cell.classList.toggle('active',i===index));if(index)el.svg.querySelectorAll('.cell')[index-1]?.classList.add('echo')}
function status(phase,token,i,total){const action=phase==='input'?`forget gate가 덜 중요한 상태를 줄이고 · input gate가 <b>“${token}”</b>을 cₜ에 기록합니다`:`output gate가 cₜ에서 현재 문맥 hₜ를 꺼내 · 다음 토큰 <b>“${token}”</b>을 고릅니다`;el.hud.innerHTML=`<b>${String(i+1).padStart(2,'0')} / ${String(total).padStart(2,'0')}</b> · ${action}`;el.stream.textContent=phase==='input'?'Tokenizer → embedding vector → input gate':'cell state cₜ → hidden state hₜ → next-token distribution';el.path.innerHTML=phase==='input'?`[question token: <em>'${token}'</em>]`:`[generated token: <em>'${token}'</em>]`}
async function play(question){const ticket=++playback;lastQuestion=question;const input=tokenise(question).slice(0,4),output=answerFor(question).slice(0,5),steps=[...input.map(token=>({token,phase:'input'})),...output.map(token=>({token,phase:'output'}))];buildCircuit(steps);el.answer.textContent='답변: ';el.replay.hidden=false;for(let i=0;i<steps.length;i++){if(ticket!==playback)return;const step=steps[i];status(step.phase,step.token,i,steps.length);setNumbers(step.token,i%4);mark(i);if(step.phase==='output')el.answer.innerHTML+=`<b>${step.token}</b> `;await wait(step.phase==='input'?820:1050);el.svg.querySelectorAll('.cell')[i]?.classList.remove('active')}if(ticket===playback){el.hud.innerHTML='<b>DONE</b> · 입력의 중요한 패턴은 장기 기억에, 현재 문맥은 단기 기억에 남아 다음 단어를 고릅니다.';el.stream.textContent='Answer complete'}}
el.form.addEventListener('submit',event=>{event.preventDefault();const question=el.input.value.trim();if(!question)return;el.form.classList.add('out');play(question)});el.replay.addEventListener('click',()=>play(lastQuestion));
